"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { WagmiProvider } from "wagmi";
import { config } from "../../config";
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
const inter = Inter({ subsets: ["latin"] });
const queryClient = new QueryClient()
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <WagmiProvider config={config}>
        <QueryClientProvider client={queryClient}>
        <Navbar/>
        {children}
        </QueryClientProvider>
        </WagmiProvider>
        </body>
    </html>
  );
}
